### ISSUE TITLE
Currently cannot build

### ISSUE THREAD

**Issue by FranklinChen** [oetiker/lshort#46]
```
$ make all
mkdir -p pdfbuild
cp src/lshort.bib pdfbuild/
lualatex --shell-escape --interaction=nonstopmode --output-directory=pdfbuild --halt-on-error lshort
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022)
 system commands enabled.
! I can't find file `lshort'.
<*> lshort

(Press Enter to retry, or Control-D to exit)
Please type another input file name
! Emergency stop.
<*> lshort

 270 words of node memory still in use:
   1 hlist, 39 glue_spec nodes
   avail lists: 2:12,3:1,4:1,5:1
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
make: *** [lshort.pdf] Error 1
```

**Comment by FranklinChen** [comment]
I meant, make it explicitly clear that all macOS users should remember to install a new GNU Make and not use Apple's own provided one, because this is really the only major gotcha.

**Comment by quark67** [comment]
I confirm that the 3.81 version of `make` provided by Apple on their computers is way too old (dated from 2006). Number 3.81 seems not very different compared to 4.3 (since several software, as browsers, have big number incrementation between versions), so, as you say "you will need reasonably recent versions" I suggest that you specifically add that a 4.3 version of `make` or newer is needed (or add that a 3.81 version will not work.

For the record, the error I obtained with the 3.81 version: 

```
make: *** No rule to make target `=', needed by `FILES'.  Stop.
```

Installing `gmake` with `brew install make` (as explained by FranklinChen at https://github.com/oetiker/lshort/issues/46#issuecomment-1168829885) and replace the command `make` by `gmake` in Terminal was the solution for me also.

As `make` can be preinstalled (in a very old version), it would be useful to specifically insist that a very recent version (probably 4.3 or more) of `make`  or  `gmake`  is need. For `git` or `pygments`, these tools are generally installed (in recent versions) by the user.
